name: backend
version: 0.1.0
publish_to: none
description: Local backend for PDO Lite Next.

environment:
  sdk: ^3.10.8

dependencies:
  data_models:
    path: ../packages/data_models
  domain:
    path: ../packages/domain
  import_engine:
    path: ../packages/import_engine
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqlite3: ^2.7.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
