name: admin_windows
description: PDO Lite Next admin and planning panel.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  data_models:
    path: ../../packages/data_models
  file_selector: ^1.0.3
  http: ^1.2.2
  shared_ui:
    path: ../../packages/shared_ui

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
